---
title: "Antiviral Treatment - 2009 Scenarios"
author: "Pragati Prasad"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mean and Cumulative with 95% CI   {.tabset}

### RL03

Antivirals  
```{r RL03, warning=FALSE, message = FALSE}

library(ggsci)
library(reshape)
library(dplyr)
library(gridExtra)
library(ggplot2)
library(egg)
library(plyr)
library(tidyr)
library(knitr)
library(kableExtra)

path <- "../model-forecasts/"

team.folder <- c("Columbia/COL/RL/", "Northeastern/RL/", "UTAustin/", "UVirginia/", "Imperial/", "Columbia/COL2/RL/", "Northeastern/RL2/", "Northeastern/RL3/")
team.abbrev <- c("COL", "NEU", "UTA", "UVA", "IMP", "COL2", "NEU", "NEU")
file.types <-c("SymIllness", "Hosp", "Deaths", "AntiviralTX")

read_overall_mean <- function(scn){
  
  cols <- c("sm.mean", "sm.perc2p5", "sm.perc97p5")

  s <- read.csv(paste0(path,team.folder[1],scn,file.types[4],"_",team.abbrev[1],".csv"))
  antivirals <- data.frame(c(s[which(s$Agegroup == "Overall" &
                                       s$Bin %in% cols),],
                             `team` = team.abbrev[1]))
  
  for(i in 2:8){
    
    if(i == 4){
      scn = gsub("RL", "RL_", scn)
    }
    if(i == 5){
      scn = gsub("_", "", scn)
    }
    if(i == 6){
      scn = paste0(scn, "_")
    }
    
    f =  paste0(path,team.folder[i],scn,file.types[4],"_",team.abbrev[i],".csv")
    if(i == 5){
      f =  paste0(path,team.folder[i],scn,file.types[4],team.abbrev[i],".csv")
    }

    if(file.exists(f)){
      s <- read.csv(f)
      if(ncol(s) > 58){
        s <- s[-1]
      }
      if(i == 7){
        team.abbrev[i] = "NEU2"
      }
      if(i == 8){
        team.abbrev[i] = "NEU3"
      }
      antivirals <- rbind.fill(antivirals, 
                               data.frame(c(s[which(s$Agegroup == "Overall" & 
                                                      s$Bin %in% cols),],`team` = team.abbrev[i])))
    }
    
  }
  weeks <- paste0("Week",1:52)
  antivirals$Cml[which(is.na(antivirals$Cml))] <- antivirals$cml[which(is.na(antivirals$Cml))]
  cml <<- antivirals[c("Cml", "team", "Bin")]
  
  long <- gather(antivirals, week, illnesses, weeks, factor_key=TRUE)
  long$week <- as.integer(gsub("Week", "", long$week))
  
  cols <- c("Bin", "team", "week", "illnesses")
  long <- long[cols]
  long_wide <- spread(long, Bin, illnesses)
  
  return(long_wide)
}

scenario <- "RL03_"

long <- read_overall_mean(scn = scenario)

ggplot(data = long, aes(x = week, y = sm.mean, group = team)) +
  geom_line(aes(color = team), lwd = 1.0) +
  geom_ribbon(aes(ymin = sm.perc2p5, ymax = sm.perc97p5, fill = team), alpha = 0.3,
              show.legend = FALSE)+
  ylab("% AntiviralTX") +
  scale_color_nejm() +
  scale_fill_nejm()


table <- cml[which(cml$Bin == "sm.mean"),]
table <- table[,-3]

table$lower <-  cml$Cml[which(cml$Bin == "sm.perc2p5")]
table$upper <-  cml$Cml[which(cml$Bin == "sm.perc97p5")]
table$Team <- table$team
table$`Cumulative % AntiviralTX` <- table$Cml
table$`95% CI` <- paste0("(", round(table$lower, 2), ", ", round(table$upper, 2), ")")

table$`Averted % AntiviralTX (RL01)` <- ifelse(table$Team %in% table1$Team, table1$`Cumulative % AntiviralTX` - table$`Cumulative % AntiviralTX`, NA)

rownames(table) <- NULL

knitr::kable(table[5:7], digits = 2, caption = "RL03: AntiviralTX", align=rep('c', 4)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


#Bar charts for age
team.folder <- c("Columbia/COL/RL/", "Northeastern/RL/", "UTAustin/", "UVirginia/", "Imperial/", "Columbia/COL2/RL/", "Northeastern/RL2/", "Northeastern/RL3/")
team.abbrev <- c("COL", "NEU", "UTA", "UVA", "IMP", "COL2", "NEU", "NEU")
file.types <-c("SymIllness", "Hosp", "Deaths", "AntiviralTX")

read_ages <- function(scn){
  
  cols <- c("sm.mean")

  s <- read.csv(paste0(path,team.folder[1],scn,file.types[4],"_",team.abbrev[1],".csv"))
  antivirals <- data.frame(c(s[which(s$Agegroup != "Overall" &
                                       s$Bin %in% cols),],
                             `team` = team.abbrev[1]))
  
  for(i in 2:8){
    
    if(i == 4){
      scn = gsub("RL", "RL_", scn)
    }
    if(i == 5){
      scn = gsub("_", "", scn)
    }
    if(i == 6){
      scn = paste0(scn, "_")
    }
    
    f =  paste0(path,team.folder[i],scn,file.types[4],"_",team.abbrev[i],".csv")
    if(i == 5){
      f =  paste0(path,team.folder[i],scn,file.types[4],team.abbrev[i],".csv")
    }

    if(file.exists(f)){
      s <- read.csv(f)
      if(ncol(s) > 58){
        s <- s[-1]
      }
      if(i == 7){
        team.abbrev[i] = "NEU2"
      }
      if(i == 8){
        team.abbrev[i] = "NEU3"
      }
      antivirals <- rbind.fill(antivirals, 
                               data.frame(c(s[which(s$Agegroup != "Overall" & 
                                                      s$Bin %in% cols),],`team` = team.abbrev[i])))
    }
    
  }
  weeks <- paste0("Week",1:52)
  antivirals$Cml[which(is.na(antivirals$Cml))] <- antivirals$cml[which(is.na(antivirals$Cml))]
  cml <- antivirals[c("Cml", "team", "Bin", "Agegroup")]
  cml$Agegroup <- sub("yr", "years", cml$Agegroup)
  cml$Agegroup <- factor(x = cml$Agegroup, levels = c("0-4 years", "5-17 years", "18-49 years", "50-64 years", "65+ years"))
  cml$Cml <- cml$Cml / 100
  
  return(cml)
}

ages <- read_ages(scn = "RL03_")
ggplot(ages, aes(fill=Agegroup, y=Cml, x=team)) + 
  geom_bar(position="fill", stat="identity") +
  ylab("Percent")+
  scale_fill_d3()

```


### RL04

Vaccine and Antivirals 
```{r RL04, warning=FALSE, message = FALSE}

scenario <- "RL04_"

long <- read_overall_mean(scn = scenario)

ggplot(data = long, aes(x = week, y = sm.mean, group = team)) +
  geom_line(aes(color = team), lwd = 1.0) +
  geom_ribbon(aes(ymin = sm.perc2p5, ymax = sm.perc97p5, fill = team), alpha = 0.3,
              show.legend = FALSE)+
  ylab("% AntiviralTX") +
  scale_color_nejm() +
  scale_fill_nejm()


table <- cml[which(cml$Bin == "sm.mean"),]
table <- table[,-3]

table$lower <-  cml$Cml[which(cml$Bin == "sm.perc2p5")]
table$upper <-  cml$Cml[which(cml$Bin == "sm.perc97p5")]
table$Team <- table$team
table$`Cumulative % AntiviralTX` <- table$Cml
table$`95% CI` <- paste0("(", round(table$lower, 2), ", ", round(table$upper, 2), ")")

table$`Averted % AntiviralTX (RL01)` <- ifelse(table$Team %in% table1$Team, table1$`Cumulative % AntiviralTX` - table$`Cumulative % AntiviralTX`, NA)

rownames(table) <- NULL

knitr::kable(table[5:7], digits = 2, caption = "RL04: Vaccine and AntiviralTX", align=rep('c', 4)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

ages <- read_ages(scn = scenario)
ggplot(ages, aes(fill=Agegroup, y=Cml, x=team)) + 
  geom_bar(position="fill", stat="identity") +
  ylab("Percent")+
  scale_fill_d3() 
```


### RL07

Vaccine, Antivirals, and School Closure when Illness incidence > 1%  
```{r RL07, warning=FALSE, message = FALSE}

scenario <- "RL07_"

long <- read_overall_mean(scn = scenario)

ggplot(data = long, aes(x = week, y = sm.mean, group = team)) +
  geom_line(aes(color = team), lwd = 1.0) +
  geom_ribbon(aes(ymin = sm.perc2p5, ymax = sm.perc97p5, fill = team), alpha = 0.3,
              show.legend = FALSE)+
  ylab("% AntiviralTX") +
  scale_color_nejm() +
  scale_fill_nejm()


table <- cml[which(cml$Bin == "sm.mean"),]
table <- table[,-3]

table$lower <-  cml$Cml[which(cml$Bin == "sm.perc2p5")]
table$upper <-  cml$Cml[which(cml$Bin == "sm.perc97p5")]
table$Team <- table$team
table$`Cumulative % AntiviralTX` <- table$Cml
table$`95% CI` <- paste0("(", round(table$lower, 2), ", ", round(table$upper, 2), ")")

table$`Averted % AntiviralTX (RL01)` <- ifelse(table$Team %in% table1$Team, table1$`Cumulative % AntiviralTX` - table$`Cumulative % AntiviralTX`, NA)

rownames(table) <- NULL

knitr::kable(table[5:7], digits = 2, caption = "RL07: Vaccine, AntiviralTX, and School Closure > 1%", align=rep('c', 4)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

ages <- read_ages(scn = scenario)
ggplot(ages, aes(fill=Agegroup, y=Cml, x=team)) + 
  geom_bar(position="fill", stat="identity") +
  ylab("Percent")+
  scale_fill_d3()
```


### RL08

Vaccine, Antivirals, School Closure on Date of Availability  
```{r RL08, warning=FALSE, message = FALSE}

scenario <- "RL08_"

long <- read_overall_mean(scn = scenario)

ggplot(data = long, aes(x = week, y = sm.mean, group = team)) +
  geom_line(aes(color = team), lwd = 1.0) +
  geom_ribbon(aes(ymin = sm.perc2p5, ymax = sm.perc97p5, fill = team), alpha = 0.3,
              show.legend = FALSE)+
  ylab("% AntiviralTX") +
  scale_color_nejm() +
  scale_fill_nejm()


table <- cml[which(cml$Bin == "sm.mean"),]
table <- table[,-3]

table$lower <-  cml$Cml[which(cml$Bin == "sm.perc2p5")]
table$upper <-  cml$Cml[which(cml$Bin == "sm.perc97p5")]
table$Team <- table$team
table$`Cumulative % AntiviralTX` <- table$Cml
table$`95% CI` <- paste0("(", round(table$lower, 2), ", ", round(table$upper, 2), ")")

table$`Averted % AntiviralTX (RL01)` <- ifelse(table$Team %in% table1$Team, table1$`Cumulative % AntiviralTX` - table$`Cumulative % AntiviralTX`, NA)

rownames(table) <- NULL

knitr::kable(table[5:7], digits = 2, caption = "RL08: Vaccine, AntiviralTX, and School Closure on Date of Availability", align=rep('c', 4)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

ages <- read_ages(scn = scenario)
ggplot(ages, aes(fill=Agegroup, y=Cml, x=team)) + 
  geom_bar(position="fill", stat="identity") +
  ylab("Percent")+
  scale_fill_d3()
```

