---
title: "File_Check"
author: "Pragati Prasad"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Files that have NA values
```{r check_na, warning=FALSE, message = FALSE}
library(dplyr)

path <- "../model-forecasts/"
team.folder <- c("Columbia/COL/RL/", "Columbia/COL2/RL/", 
                 "Columbia/COL/EPI1/", "Columbia/COL2/EPI1/", 
                 "Columbia/COL/EPI2/", "Columbia/COL2/EPI2/",
                 "Northeastern/RL/","Northeastern/RL2/","Northeastern/RL3/",
                 "Northeastern/EPI1/","Northeastern/EPI2/", 
                 "UTAustin/", 
                 "UVirginia/", 
                 "Imperial/")

for(t in team.folder){
  list <- list.files(path = paste0(path, t), pattern = ".csv")
  for(l in list){
    r <- read.csv(paste0(path, t, l))
    r <- as.data.frame(r)
    invalid <- sapply(r, function(x) ifelse(any(is.nan(x)), NA, x))
    if(invalid){
      print(paste0(path, t, l))
    }
  }
  
}
```


## Files that have NaN values
```{r check_nan, warning=FALSE, message = FALSE}

path <- "../model-forecasts/"
team.folder <- c("Columbia/COL/RL/", "Columbia/COL2/RL/", 
                 "Columbia/COL/EPI1/", "Columbia/COL2/EPI1/", 
                 "Columbia/COL/EPI2/", "Columbia/COL2/EPI2/",
                 "Northeastern/RL/","Northeastern/RL2/","Northeastern/RL3/",
                 "Northeastern/EPI1/","Northeastern/EPI2/", 
                 "UTAustin/", 
                 "UVirginia/", 
                 "Imperial/")

for(t in team.folder){
  list <- list.files(path = paste0(path, t), pattern = ".csv")
  for(l in list){
    r <- read.csv(paste0(path, t, l))
    r <- as.data.frame(r)
    invalid <- sapply(r, function(x) ifelse(any(is.nan(x)), NA, x))
    if(invalid){
      print(paste0(path, t, l))
    }
  }
  
}
```

